theme: dark
panel:
  position: top
sections:
  - name: Applications
    icon: /usr/share/icons/hicolor/48x48/apps/utilities-terminal.png
    items:
      - name: Firefox
        type: application
        command: firefox
        icon: /usr/share/icons/hicolor/48x48/apps/firefox.png
      - name: Terminal
        type: application
        command: gnome-terminal
  - name: Scripts
    icon: /usr/share/icons/hicolor/48x48/apps/utilities-system-monitor.png
    items:
      - name: Update Script
        type: script
        command: /home/user/update.sh
  - name: Websites
    icon: /usr/share/icons/hicolor/48x48/apps/internet-web-browser.png
    items:
      - name: Open GitHub
        type: url
        command: https://github.com
